### ISSUE TITLE
can't run

### ISSUE THREAD

**Issue by ZhLinda** [devyuan/IAPProductTool#2]
/Users/lee/.rvm/rubies/ruby-2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.121.0/spaceship/lib/spaceship/module.rb:2:in `<module:Spaceship>': uninitialized constant Spaceship::Pathname (NameError)
	from /Users/lee/.rvm/rubies/ruby-2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.121.0/spaceship/lib/spaceship/module.rb:1:in `<top (required)>'
	from /Users/lee/.rvm/rubies/ruby-2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.121.0/spaceship/lib/spaceship/tunes/display_family.rb:1:in `require_relative'
	from /Users/lee/.rvm/rubies/ruby-2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.121.0/spaceship/lib/spaceship/tunes/display_family.rb:1:in `<top (required)>'
	from /Users/lee/.rvm/rubies/ruby-2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.121.0/spaceship/lib/spaceship/du/du_client.rb:2:in `require_relative'
	from /Users/lee/.rvm/rubies/ruby-2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.121.0/spaceship/lib/spaceship/du/du_client.rb:2:in `<top (required)>'
	from /Users/lee/.rvm/rubies/ruby-2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.121.0/spaceship/lib/spaceship/tunes/tunes_client.rb:3:in `require_relative'
	from /Users/lee/.rvm/rubies/ruby-2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.121.0/spaceship/lib/spaceship/tunes/tunes_client.rb:3:in `<top (required)>'
	from /Users/lee/.rvm/gems/ruby-2.4.0@global/gems/fastlane-2.121.0/spaceship/lib/spaceship/two_step_or_factor_client.rb:2:in `require_relative'
	from /Users/lee/.rvm/gems/ruby-2.4.0@global/gems/fastlane-2.121.0/spaceship/lib/spaceship/two_step_or_factor_client.rb:2:in `<top (required)>'
	from /Users/lee/.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/lee/.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/lee/.rvm/rubies/ruby-2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.121.0/spaceship/lib/spaceship/client.rb:892:in `<top (required)>'
	from /Users/lee/.rvm/gems/ruby-2.4.0@global/gems/fastlane-2.121.0/spaceship/lib/spaceship.rb:3:in `require_relative'
	from /Users/lee/.rvm/gems/ruby-2.4.0@global/gems/fastlane-2.121.0/spaceship/lib/spaceship.rb:3:in `<top (required)>'
	from /Users/lee/.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:130:in `require'
	from /Users/lee/.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:130:in `rescue in require'
	from /Users/lee/.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:35:in `require'
	from /Users/lee/Desktop/混淆工具/IAPProductTool-master/iap_helper.rb:4:in `<top (required)>'
	from /Users/lee/.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/lee/.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from index.rb:5:in `<main>'

**Comment by ZhLinda** [comment]
一周之前还能正常使用，今天更新了系统和commomd tool、fastlane，运行后报错。

**Comment by ZhLinda** [comment]
fastlane更新的问题，已解决
